# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - fallback-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - fallback-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: fallback-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test

